services:
  # backend:
  #   container_name: backend
  #   build: .
  #   env_file:
  #     - .env
  #   ports: 
  #     - "5000:5000"
  #   depends_on:
  #     - db

  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - ./db_data:/var/lib/postgresql/data